import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/shared/breadcrumbs";
import { LegalLayout } from "@/components/shared/legal-layout";
import { PageContainer } from "@/components/shared/page-container";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: "Educational content disclaimer for Happy Kids Academy.",
  alternates: { canonical: "/disclaimer" },
};

const LAST_UPDATED = "July 30, 2026";

export default function DisclaimerPage() {
  return (
    <PageContainer>
      <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Disclaimer" }]} />
      <LegalLayout title="Disclaimer" lastUpdated={LAST_UPDATED}>
        <section>
          <h2>Educational purpose only</h2>
          <p>
            Happy Kids Academy is designed to make early learning fun — it is a supplementary
            activity, not a substitute for formal schooling, curriculum-based instruction, or
            professional educational or developmental assessment. Every child learns at their own
            pace; please use your judgment alongside a teacher, caregiver, or specialist as needed.
          </p>
        </section>

        <section>
          <h2>Content accuracy</h2>
          <p>
            We take care to keep letters, numbers, facts, translations, and pronunciations accurate.
            Even so, language and regional conventions vary (for example, in Gujarati and Hindi
            transliteration), and we can&apos;t guarantee the content is free of every error. If you
            spot something incorrect, we&apos;d genuinely like to know.
          </p>
        </section>

        <section>
          <h2>Voice and audio</h2>
          <p>
            Spoken pronunciation is generated by your device&apos;s or browser&apos;s built-in
            text-to-speech engine. Voice quality, accent, and availability depend entirely on your
            device and browser, and are outside of our control.
          </p>
        </section>

        <section>
          <h2>Parental supervision</h2>
          <p>
            This app is intended for young children to use with a parent, guardian, or teacher nearby,
            especially for first-time use, device settings, and screen-time decisions that are best
            made by the adults in a child&apos;s life.
          </p>
        </section>

        <section>
          <h2>No liability</h2>
          <p>
            Use of this app and its content is at your own discretion. Happy Kids Academy and its
            creators accept no liability for outcomes resulting from use of, or reliance on, the
            content provided.
          </p>
        </section>
      </LegalLayout>
    </PageContainer>
  );
}
